export const COMPANY_CATEGORIES = [
  { name: 'Bares', id: 'bars' },
  { name: 'Restaurantes', id: 'restaurants' },
  { name: 'Cafeterías', id: 'cafes' },
  { name: 'Panaderías y pastelerías', id: 'bakeries' },
  { name: 'Food trucks', id: 'food-trucks' },
  { name: 'Casinos (comedores empresariales)', id: 'corporate-cafeterias' },
  { name: 'Discotecas', id: 'nightclubs' },
  { name: 'Cervecerías artesanales', id: 'craft-breweries' },
  { name: 'Supermercados', id: 'supermarkets' },
  { name: 'Minimarkets', id: 'convenience-stores' },
  { name: 'Ferreterías', id: 'hardware-stores' },
  { name: 'Tiendas de ropa', id: 'clothing-stores' },
  { name: 'Tiendas de calzado', id: 'shoe-stores' },
  { name: 'Librerías y papelerías', id: 'bookstores' },
  { name: 'Jugueterías', id: 'toy-stores' },
  { name: 'Tiendas de electrónica y tecnología', id: 'electronics-stores' },
  { name: 'Almacenes de barrio', id: 'corner-stores' },
  { name: 'Florerías', id: 'flower-shops' },
  { name: 'Servicios de transporte', id: 'transport-services' },
  { name: 'Servicios de turismo', id: 'tourism-services' },
  { name: 'Servicios de limpieza', id: 'cleaning-services' },
  { name: 'Servicios de mantenimiento', id: 'maintenance-services' },
  { name: 'Estéticas y salones de belleza', id: 'beauty-salons' },
  { name: 'Barberías', id: 'barber-shops' },
  { name: 'Gimnasios y centros de fitness', id: 'gyms' },
  { name: 'Centros de yoga y pilates', id: 'yoga-studios' },
  { name: 'Servicios de reparación de electrodomésticos', id: 'appliance-repair' },
  { name: 'Servicios de marketing y publicidad', id: 'marketing-agencies' },
  { name: 'Empresas de eventos y banquetería', id: 'event-planners' },
  { name: 'Jardines infantiles', id: 'preschools' },
  { name: 'Colegios particulares', id: 'private-schools' },
  { name: 'Centros de educación técnica y profesional', id: 'technical-schools' },
  { name: 'Institutos de idiomas', id: 'language-schools' },
  { name: 'Centros de formación artística', id: 'art-schools' },
  { name: 'Empresas agrícolas', id: 'agricultural-companies' },
  { name: 'Empresas pesqueras', id: 'fishing-companies' },
  { name: 'Industrias textiles', id: 'textile-industries' },
  { name: 'Empresas metalmecánicas', id: 'metalworking-companies' },
  { name: 'Industrias químicas', id: 'chemical-industries' },
  { name: 'Empresas de construcción', id: 'construction-companies' },
  { name: 'Empresas de minería', id: 'mining-companies' },
  { name: 'Clínicas y hospitales', id: 'clinics' },
  { name: 'Centros médicos', id: 'medical-centers' },
  { name: 'Laboratorios clínicos', id: 'clinical-labs' },
  { name: 'Farmacias', id: 'pharmacies' },
  { name: 'Centros de kinesiología', id: 'kinesiology-centers' },
  { name: 'Centros de fisioterapia', id: 'physiotherapy-centers' },
  { name: 'Ópticas', id: 'optical-stores' },
  { name: 'Centros veterinarios', id: 'veterinary-clinics' },
  { name: 'Bancos', id: 'banks' },
  { name: 'Fintech', id: 'fintech-companies' },
  { name: 'Empresas de software', id: 'software-companies' },
  { name: 'Empresas de desarrollo web', id: 'web-development-companies' },
  { name: 'Empresas de ciberseguridad', id: 'cybersecurity-companies' },
  { name: 'Call centers', id: 'call-centers' },
  { name: 'Productoras audiovisuales', id: 'audiovisual-producers' },
  { name: 'Editoras y editoriales', id: 'publishers' },
  { name: 'Tiendas de artesanía', id: 'craft-stores' },
  { name: 'Museos privados', id: 'private-museums' },
  { name: 'Galerías de arte', id: 'art-galleries' },
  { name: 'Centros culturales', id: 'cultural-centers' },
  { name: 'Empresas de transporte de carga', id: 'freight-companies' },
  { name: 'Empresas de mensajería y courier', id: 'courier-companies' },
  { name: 'Agencias de mudanzas', id: 'moving-companies' },
  { name: 'Empresas de logística y distribución', id: 'logistics-companies' },
  { name: 'Inmobiliarias', id: 'real-estate-agencies' },
  { name: 'Corredoras de propiedades', id: 'property-brokers' },
  { name: 'Empresas de arriendo de equipos', id: 'equipment-rental' },
  { name: 'Funerarias', id: 'funeral-homes' },
  { name: 'Centros de juegos infantiles', id: 'play-centers' },
  { name: 'Casinos de juegos', id: 'gaming-casinos' },
  { name: 'Parques de diversiones', id: 'amusement-parks' },
  { name: 'Zoológicos', id: 'zoos' },
  { name: 'Acuarios', id: 'aquariums' },
  { name: 'Tiendas de mascotas', id: 'pet-stores' },
  { name: 'Estaciones de servicio', id: 'gas-stations' },
  { name: 'Talleres mecánicos', id: 'mechanic-shops' },
  { name: 'Lavados de autos', id: 'car-washes' },
  { name: 'Tiendas de bicicletas', id: 'bike-shops' },
  { name: 'Parques de conservación', id: 'conservation-parks' },
  { name: 'Clínicas dentales', id: 'dental-clinics' },
  { name: 'Tiendas de cosméticos', id: 'cosmetics-stores' },
  { name: 'Estudios de tatuajes', id: 'tattoo-studios' },
  { name: 'Estudios de piercing', id: 'piercing-studios' },
  { name: 'Consultoras de recursos humanos', id: 'hr-consultants' },
  { name: 'Empresas de seguridad', id: 'security-companies' },
  { name: 'Tiendas de música', id: 'music-stores' },
  { name: 'Estudios de grabación', id: 'recording-studios' },
  { name: 'Academias de baile', id: 'dance-schools' },
];
